### ISSUE TITLE
Ambiguous RESET_STREAM

### ISSUE THREAD

**Issue by kixelated** [ietf-wg-webtrans/draft-ietf-webtrans-http3#31] opened 2021-02-23 03:49 UTC
If a peer receives a RESET_STREAM message before it receives the first few bytes of the stream, then it is unable associate the RESET_STREAM with a protocol or session. This can occur if the STREAM packet is lost but the RESET_STREAM is not.

As a consequence, if a WebTransport client closes a stream with an error code, then it's not guaranteed to be received by the server. Worse yet, a reset client-initiated bidirectional stream may be confused for a HTTP/3 request and cause intended consequences.

**Comment by afrind** [comment] 2021-02-23 16:37
Can you give a more concrete example of when this is a problem?

You are saying the client opened a unidirectional or bidirectional WT stream, sent some data, then reset it.  The server receives only the reset, or some fraction of the data but not enough to figure out which session the stream belongs to.  I think this is fine and the server just discards any partial data on this stream.

If the application needs to receive the data (even just an error code) in the stream, then the client shouldn't reset it, but instead, send some application level close signal that is delivered reliably on the stream.

I don't see how an H3 server could act on any stream data from the client without seeing the beginning of the stream, so I don't think there's much concern about this being served as an H3 request.

**Comment by kixelated** [comment] 2021-02-23 19:14
Sure. I suppose the problem is the reliable delivery of error codes. 

If the application closes a stream with an integer code via the [WebTransport API](https://w3c.github.io/webtransport/#dom-outgoingstream-abortwriting), then I would expect that code to be reliably delivered to the other peer. This ambiguous RESET_STREAM case opens the possibility of the code not being associated with a WebTransport session, and thus not delivered, depending on packet loss.

**Comment by LPardue** [comment] 2021-02-23 19:23
Iiuc the problem is if the stream is reset before the Web Transport frame is processed (as far the *current* spec says). That frame associates the stream to the web transport session. A peer that receives the RESET_STREAM know something was cancelled but not whether it was a normal request or a webtransport stream. 

This highlights a challenge with retconning what bidirectional streams mean for a H3 stack.

**Comment by afrind** [comment] 2021-02-23 19:30
I can construct an application where it's important that the peer knows about every stream that gets created, even if it is reset before anything interesting happens, but it strikes me as a bit fringy.  Can you give a concrete example where the WT endpoint missing the reset stream entirely is problematic?

**Comment by LPardue** [comment] 2021-02-23 19:38
The only example I can think of relates to session pooling and wanting different concurrency limits in sessions. Since we decided to focus on single sessions for now, my example I'd moot. I'd be interested to know Luke's example

**Comment by kixelated** [comment] 2021-02-23 23:15
> I can construct an application where it's important that the peer knows about every stream that gets created, even if it is reset before anything interesting happens, but it strikes me as a bit fringy. Can you give a concrete example where the WT endpoint missing the reset stream entirely is problematic?

Ironically, the best example is an application implementing a replacement for MAX_STREAMS, if it's needed on a per session basis. Peers can't set a cumulative limit if they disagree on the number of streams created.

And yeah, it's pretty easy to imagine an application that uses stream resets. The WebTransport API makes stream closure seem reliable, when really there's a small chance that it gets silently dropped.

**Comment by LPardue** [comment] 2021-02-24 00:15
This seems like another case of where a "session layer" over QUIC would assist. The trouble is, in my limited understanding of the W3C WebTransport API, that it wants to use a QUIC transport feature to manage WebTransport sessions. It is going to be let down by the fact the transport behaves differently than it wishes. 

draft-ietf-webtrans-http3-00 defines the WEBTRANSPORT_STREAM HTTP/3 frame for initiating WebTransport streams. So it probably needs an equivalent frame for closing WebTransport streams. This could be sent on the stream itself, on a new "webtransport session control stream", or on the global control stream.

**Comment by afrind** [comment] 2021-02-24 17:00
> This could be sent on the stream itself, on a new "webtransport session control stream", or on the global control stream.

By 'on the stream itself', do you mean on the CONNECT stream that established the session?  The current draft disables framing on WT streams.  It could be a message like QPACK, where streams that are cancelled have an application level signal.

**Comment by LPardue** [comment] 2021-02-24 17:07
> By 'on the stream itself', do you mean on the CONNECT stream that established the session?

No. If I understand (and that's a big if) the design of draft-ietf-webtrans-http3-00 requires

step 1) use extended  CONNECT on client bidi stream to create a WebTransport session

step 2) create WebTransport stream on different client bidi stream using WEBTRANSPORT_STREAM frame https://tools.ietf.org/html/draft-ietf-webtrans-http3-00#section-4.2

My suggestion wasn't about retiring WebTransport sessions, but retiring streams robustly at the application layer. If you created a stream using an H3 frame, retire it with an H3 frame.

Although we adopted draft-ietf-webtrans-http3-00, I;m not sure how much of the design is appropriate/relevant to the non-pooling constraints we have added. So i guess my current understanding could be subject to change.

**Comment by afrind** [comment] 2021-02-24 18:11
The current draft uses a 'TV' frame on streams created in step 2) that makes sending additional frames on those streams impossible.  I'm suggesting we could use the stream created in step 1) as a "webtransport session control stream", if needed.

**Comment by LPardue** [comment] 2021-02-24 18:16
Ah yes, I overlooked that. In that case I agree

**Comment by vasilvv** [comment] 2021-07-22 23:28
I was thinking about how to make those more reliable.  One way would be to send a capsule with something like "stream X associated with this transport has been reset".  That doesn't work, because the peers don't have consistent stream IDs across possible HTTP proxies.

I think the approach we should probably go with is "stream resets are usually not reliable".  As an API caveat, we should make sure that when the connection is dedicated, all resets with WebTransport error codes are followed to the client, since those are unambiguous.

**Comment by vasilvv** [comment] 2021-11-05 19:39
This was fixed in #59.

**Closed by vasilvv** 2021-11-05 19:39 UTC
